### ISSUE TITLE
Не показывается диалог создания стиля

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb_qgis#6]
Установил QGIS 1:2.8.1-0+20trusty6,  поставил nextgisweb_qgis.
Пункт # Only for latest QGIS version (not for 2.8) - не выполнял

В NGW появилась ссылка "QGIS vector style", открывается пустая форма, в консоли сообщение:

```
Exception when serving /resource/widget
Traceback (most recent call last):
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 223, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 198, in invoke_subrequest
    response = handle_request(request)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/home/trolleway/ngw/nextgisweb/nextgisweb/resource/api.py", line 204, in resource_exception_tween
    response = handler(request)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 353, in rendered_view
    result = view(context, request)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 507, in _requestonly_view
    response = view(request)
  File "/home/trolleway/ngw/nextgisweb/nextgisweb/pyramid/util.py", line 14, in wrapped
    return f(request, *args, **kwargs)
  File "/home/trolleway/ngw/nextgisweb/nextgisweb/resource/view.py", line 173, in widget
    .filter_by(id=parent_id).one()
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2323, in one
    ret = list(self)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2366, in __iter__
    return self._execute_and_instances(context)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2381, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/home/trolleway/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) relation "qgis_vector_style" does not exist
LINE 2: ... mapserver_style.id = resource.id LEFT OUTER JOIN qgis_vecto...
                                                             ^
 'SELECT resource.id AS resource_id, resource.cls AS resource_cls, resource.parent_id AS resource_parent_id, resource.keyname AS resource_keyname, resource.display_name AS resource_display_name, resource.owner_user_id AS resource_owner_user_id, resource.description AS resource_description, resource_group.id AS resource_group_id, mapserver_style.id AS mapserver_style_id, mapserver_style.xml AS mapserver_style_xml, qgis_vector_style.id AS qgis_vector_style_id, qgis_vector_style.qml_fileobj_id AS qgis_vector_style_qml_fileobj_id, raster_style.id AS raster_style_id, wfsserver_service.id AS wfsserver_service_id, wmsserver_service.id AS wmsserver_service_id, vector_layer.id AS vector_layer_id, vector_layer.tbl_uuid AS vector_layer_tbl_uuid, vector_layer.geometry_type AS vector_layer_geometry_type, vector_layer.srs_id AS vector_layer_srs_id, vector_layer.feature_label_field_id AS vector_layer_feature_label_field_id, raster_layer.id AS raster_layer_id, raster_layer.fileobj_id AS raster_layer_fileobj_id, raster_layer.xsize AS raster_layer_xsize, raster_layer.ysize AS raster_layer_ysize, raster_layer.band_count AS raster_layer_band_count, raster_layer.srs_id AS raster_layer_srs_id, postgis_connection.id AS postgis_connection_id, postgis_connection.hostname AS postgis_connection_hostname, postgis_connection.database AS postgis_connection_database, postgis_connection.username AS postgis_connection_username, postgis_connection.password AS postgis_connection_password, postgis_layer.id AS postgis_layer_id, postgis_layer.connection_id AS postgis_layer_connection_id, postgis_layer.schema AS postgis_layer_schema, postgis_layer."table" AS postgis_layer_table, postgis_layer.column_id AS postgis_layer_column_id, postgis_layer.column_geom AS postgis_layer_column_geom, postgis_layer.geometry_type AS postgis_layer_geometry_type, postgis_layer.geometry_srid AS postgis_layer_geometry_srid, postgis_layer.srs_id AS postgis_layer_srs_id, postgis_layer.feature_label_field_id AS postgis_layer_feature_label_field_id, webmap.id AS webmap_id, webmap.root_item_id AS webmap_root_item_id, webmap.bookmark_resource_id AS webmap_bookmark_resource_id, webmap.extent_left AS webmap_extent_left, webmap.extent_right AS webmap_extent_right, webmap.extent_bottom AS webmap_extent_bottom, webmap.extent_top AS webmap_extent_top, wmsclient_connection.id AS wmsclient_connection_id, wmsclient_connection.url AS wmsclient_connection_url, wmsclient_connection.version AS wmsclient_connection_version, wmsclient_connection.username AS wmsclient_connection_username, wmsclient_connection.password AS wmsclient_connection_password, wmsclient_connection.capcache_xml AS wmsclient_connection_capcache_xml, wmsclient_connection.capcache_json AS wmsclient_connection_capcache_json, wmsclient_connection.capcache_tstamp AS wmsclient_connection_capcache_tstamp, wmsclient_layer.id AS wmsclient_layer_id, wmsclient_layer.connection_id AS wmsclient_layer_connection_id, wmsclient_layer.wmslayers AS wmsclient_layer_wmslayers, wmsclient_layer.imgformat AS wmsclient_layer_imgformat, wmsclient_layer.srs_id AS wmsclient_layer_srs_id, srs_1.id AS srs_1_id, srs_1.display_name AS srs_1_display_name, srs_1.minx AS srs_1_minx, srs_1.miny AS srs_1_miny, srs_1.maxx AS srs_1_maxx, srs_1.maxy AS srs_1_maxy, srs_2.id AS srs_2_id, srs_2.display_name AS srs_2_display_name, srs_2.minx AS srs_2_minx, srs_2.miny AS srs_2_miny, srs_2.maxx AS srs_2_maxx, srs_2.maxy AS srs_2_maxy, srs_3.id AS srs_3_id, srs_3.display_name AS srs_3_display_name, srs_3.minx AS srs_3_minx, srs_3.miny AS srs_3_miny, srs_3.maxx AS srs_3_maxx, srs_3.maxy AS srs_3_maxy, srs_4.id AS srs_4_id, srs_4.display_name AS srs_4_display_name, srs_4.minx AS srs_4_minx, srs_4.miny AS srs_4_miny, srs_4.maxx AS srs_4_maxx, srs_4.maxy AS srs_4_maxy \nFROM resource LEFT OUTER JOIN resource_group ON resource_group.id = resource.id LEFT OUTER JOIN mapserver_style ON mapserver_style.id = resource.id LEFT OUTER JOIN qgis_vector_style ON qgis_vector_style.id = resource.id LEFT OUTER JOIN raster_style ON raster_style.id = resource.id LEFT OUTER JOIN wfsserver_service ON wfsserver_service.id = resource.id LEFT OUTER JOIN wmsserver_service ON wmsserver_service.id = resource.id LEFT OUTER JOIN vector_layer ON vector_layer.id = resource.id LEFT OUTER JOIN raster_layer ON raster_layer.id = resource.id LEFT OUTER JOIN postgis_connection ON postgis_connection.id = resource.id LEFT OUTER JOIN postgis_layer ON postgis_layer.id = resource.id LEFT OUTER JOIN webmap ON webmap.id = resource.id LEFT OUTER JOIN wmsclient_connection ON wmsclient_connection.id = resource.id LEFT OUTER JOIN wmsclient_layer ON wmsclient_layer.id = resource.id LEFT OUTER JOIN srs AS srs_1 ON srs_1.id = vector_layer.srs_id LEFT OUTER JOIN srs AS srs_2 ON srs_2.id = raster_layer.srs_id LEFT OUTER JOIN srs AS srs_3 ON srs_3.id = postgis_layer.srs_id LEFT OUTER JOIN srs AS srs_4 ON srs_4.id = wmsclient_layer.srs_id \nWHERE resource.id = %(id_1)s' {'id_1': u'18'}
```

**Comment by trolleway** [comment]
Такая же ошибка  теперь при создании стиля Mapserver

**Comment by drnextgis** [comment]
Забыл проинициализировать БД?

**Comment by trolleway** [comment]
Действительно. Я думал, что её не надо было инициализировать, а оказалось надо. 
https://github.com/nextgis/docs_ngweb/commit/d48987ba373269ba7e5c9c0301e5be387355d508
